### ISSUE TITLE
Error Project Load

### ISSUE THREAD

**Issue by chuongmep** [DomCR/ACadSharp#1]
Dear DomCR,
I see you has miss test in project, can upload, thanks you.I see project useful.
![image](https://user-images.githubusercontent.com/31106432/112131528-390b6680-8bfc-11eb-9550-a2b6f7d43977.png)

**Comment by DomCR** [comment]
Hi @chuongmep,
The tests are in a early stage, in which I'm looking for the best way to test the library, I will publish the tests project as soon as they are useful.
