### ISSUE TITLE
How to detect draw order of objects

### ISSUE THREAD

**Issue by Nevors** [DomCR/ACadSharp#113]
**Describe the bug**
I have two dwg files with difference draw order of two objects

**To Reproduce**
Parse two file and serialize to JSON. There is no difference except for modification date. They have the same draw order.

**Expected behavior**
I think these object should have different position in Objects array.

**Screenshots**
![image](https://user-images.githubusercontent.com/28799561/225572751-94a139f7-394b-412e-98b2-a6d8427fedb7.png)
![image](https://user-images.githubusercontent.com/28799561/225573088-03cf6bb2-5edf-485f-92fd-4d8232ea3432.png)

```
using ACadSharp;
using ACadSharp.IO;
using Newtonsoft.Json;

void onNotification(object sender, NotificationEventArgs e)
{
    Console.WriteLine(e.Message);
}

CadDocument doc = DwgReader.Read("./draworder.dwg", onNotification);

var json = JsonConvert.SerializeObject(doc, new Newtonsoft.Json.JsonSerializerSettings {
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
    Formatting = Formatting.Indented,
    PreserveReferencesHandling = PreserveReferencesHandling.Objects,
});

await File.WriteAllTextAsync("output1.json", json);
```

Correct me if i test it wrong.

**Comment by Nevors** [comment]
Any updates?

**Comment by Nevors** [comment]
@DomCR i tried to parse SORTENTSTABLE from files. As you can see in screenshot below, it looks like draw order.

Left side is the first screenshot from issue description, right is the second. 437 is green shape, 483 is blue shape.
![image](https://user-images.githubusercontent.com/28799561/228547254-427af480-ca2d-47c5-b601-7c79566e0c5c.png)

What do you think of it? If it helps, i will push changes later.

**Comment by DomCR** [comment]
now I see what you mean, `ACadSharp` should implement [this object](https://help.autodesk.com/view/OARX/2021/ENU/?guid=GUID-462F4378-F850-4E89-90F2-3C1880F55779) for that, by now this is not implemented but I can open a branch to implement this object into the library.

If you have a PR with an implementation feel free to push it into master and I'll be glad to review it, by now I'll open a branch to implement the `SORTENTSTABLE` object.
