### ISSUE TITLE
I cannot read a specific dwg file in c#

### ISSUE THREAD

**Issue by ebadmail** [DomCR/ACadSharp#130]
Hello ACadSharp Team,

I’m currently experiencing an issue while trying to read a file in C# using your library. The error message I receive is as follows:

```
System.ArgumentOutOfRangeException: TimeSpan overflowed because the duration is too long.
at ACadSharp.IO.DWG.DwgStreamReaderBase.ReadTimeSpan()
at ACadSharp.IO.DWG.DwgHeaderReader.Read(Int32 acadMaintenanceVersion, DwgHeaderHandlesCollection& objectPointers)
at ACadSharp.IO.DwgReader.ReadHeader()
at ACadSharp.IO.DwgReader.Read()
at ACadSharp.IO.DwgReader.Read(String filename, DwgReaderConfiguration configuration, NotificationEventHandler notification)
```

The file looks like this:

![image](https://github.com/DomCR/ACadSharp/assets/17347816/a7c5f045-9e37-488b-ac2f-eebf1d9f76c7)

I kindly request your assistance in resolving this issue.

Thank you.

**Comment by DomCR** [comment]
Hi @ebadmail,

can you provide the file or an equivalent of it to be able to reproduce the error?

**Comment by ebadmail** [comment]
Hi @DomCR,

Thank you for your response. I'm unable to share the file directly as I'm not the owner. However, I attempted to troubleshoot the problem by modifying the code in DwgStreamReaderBase.cs:

```
public TimeSpan ReadTimeSpan()
{
    long hours = this.ReadBitLong();
    long milliseconds = this.ReadBitLong();
...
}
```

The output I obtained was:

hours = 313330304;
milliseconds = 5246039;

To further investigate, I created a new file using the same entities, which worked successfully.

Please let me know if there's any additional information I can provide.

Thank you.

**Comment by DomCR** [comment]
It seems that the error is in the TimeSpan conversion, but I don't feel comfortable adding a try catch or an implementation without a way to test it and make sure that does not have any other repercussion.

**Comment by ebadmail** [comment]
Here are the files:

[Files.zip](https://github.com/DomCR/ACadSharp/files/11509672/Files.zip)

My workaround:

```
public TimeSpan ReadTimeSpan()
{
	long hours = this.ReadBitLong();
	long milliseconds = this.ReadBitLong();

	// Handle potential overflow
	if (hours < 0 || hours > TimeSpan.MaxValue.TotalHours || milliseconds < 0 || milliseconds > TimeSpan.MaxValue.TotalMilliseconds)
	{
		return TimeSpan.FromHours(0) + TimeSpan.FromMilliseconds(0);

	}

	return TimeSpan.FromHours(hours) + TimeSpan.FromMilliseconds(milliseconds);
}
```

Some articles about this issue:

https://forums.autodesk.com/t5/autocad-forum/negative-editing-time-in-document-properties/td-p/4849303
https://help.autodesk.com/view/ACD/2018/ENU/?guid=GUID-990C8D36-CD20-48C0-A711-4F03B33C084C
https://www.cadtutor.net/forum/topic/50762-negative-total-editing-time/
https://office-watch.com/2023/dont-trust-total-editing-time-in-word/

**Comment by DomCR** [comment]
I've tested your solution, works fine, thanks for the docs also.

Thanks, great job!
