### ISSUE TITLE
Simple POINT/TEXT DWG only loads a single point

### ISSUE THREAD

**Issue by mattbrownfaro** [DomCR/ACadSharp#134]
**Describe the bug**
This DWG should have 200+ objects. Only returns a single point from ACadSharp

**Expected behavior**
Read should return Points and Text labels, and a polyline or 2

**Screenshots**
This is how it looks in True View
![Snag_183ea638](https://github.com/DomCR/ACadSharp/assets/9598498/fd79c301-cc40-4b31-bb96-7578d2afa60f)

**Additional context**
I ran it thru ConvertCloud.com and it loads correctly in ACadSharp. QueenCity DXF is another Point/Text/Lines drawing with similar results.

[23 wheeling.zip](https://github.com/DomCR/ACadSharp/files/11532199/23.wheeling.zip)
[2140QUEENCITY.zip](https://github.com/DomCR/ACadSharp/files/11533021/2140QUEENCITY.zip)

**Comment by DomCR** [comment]
Hi @mattbrownfaro,

Looking at the file I've found a bug in the `ObjectReader` pushing the changes now.

**Comment by mattbrownfaro** [comment]
Fixed!!! Well done Dom! Thank you.
