### ISSUE TITLE
Reactors dictionary not resolved

### ISSUE THREAD

**Issue by mme1950** [DomCR/ACadSharp#146]
Many entites have a list of Reactors, represented by a Dictionary handle-->object.

The Dictionary only contains the keys but not the resolved values = object references.

Expected:
In The CadTemplate.Build method line 55 ff. the list of ReactorsHandles shall be used to fill the dictionaries with references resolved by the object handles. However the list of ReactorsHandles is empty.

The list of ReactorsHandles should be filled in method DwgObjectSectionReader.readReactorsAndDictionaryHandle. But instead of adding the handles to the ReactorsHandles list the handles are directly added into Reactors dictionary.

Code in DwgObjectSectionReader.readReactorsAndDictionaryHandle should be changed as follows:

<pre>
     for (int i = 0; i < numberOfReactors; ++i)
	 //[Reactors (soft pointer)]
	 //template.CadObject.Reactors.Add(this.handleReference(), null);
	 template.ReactorsHandles.Add(this.handleReference());
</pre>

**Comment by DomCR** [comment]
Good spot!! opening a branch to fix it.

Thanks!
