### ISSUE TITLE
Hatch.BoundaryPath.Ellipse: MinorToMajorRatio not read

### ISSUE THREAD

**Issue by mme1950** [DomCR/ACadSharp#147]
`Hatch.BoundaryPath.Ellipse` is used to describe an edge in a boundery path for the Hatch entity.

The ratio of minor to major axis is stored with DXF group code 40.
This value is read into the `Radius` property. This is, I suppose, not intended. The `Radius` property has no relevance for an elliptical art. 

The DXF documentation states that is the ratio in percent. This seems, however, not to be true.

Anyhow - the value should be stored into `MinorToMajorRatio`  property.

**Comment by DomCR** [comment]
For some reason that I don't remember `Hatch.BoundaryPath.Ellipse` inherits `Hatch.BoundaryPath.Arc` which is wrong... I'll fix that.

Thanks!
