### ISSUE TITLE
Dimension Text default logic and formatting

### ISSUE THREAD

**Issue by mme1950** [DomCR/ACadSharp#151]
The `Dimension.Text` property should return an empty or explicit text when the value is not null.
It should return a default text, i. e. the formatted Measurement, when the value is null.
The implementation handles null and empty in the same way.

<pre>
		/// <summary>
		/// Dimension text explicitly entered by the user
		/// </summary>
		/// <remarks>
		/// Optional; default is the measurement.
		/// If null, the dimension measurement is drawn as the text, 
		/// if ““ (one blank space), the text is suppressed.Anything else is drawn as the text
		/// </remarks>
		[DxfCodeValue(DxfReferenceType.Optional, 1)]
		public string Text
		{
			get { return string.IsNullOrEmpty(_text) ? this.Measurement.ToString() : this._text; }
			set { this._text = value; }
		}
</pre>

I would propose to format the `Measurement` value after rounding to `Dimension.Style.DecimalPlaces` and using the `Dimension.Style.DecimalSeparator`. Perhaps it even makes sense to add unit string etc.

**Comment by mme1950** [comment]
[This documentation](https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-EDD54EAC-A339-4EBA-AEA6-EC8066505E2B) contains the description for group code 1 as given in the comment above.

_Dimension text explicitly entered by the user. Optional; default is the measurement. If null or “<>”, the dimension measurement is drawn as the text, if ““ (one blank space), the text is suppressed. Anything else is drawn as the text_.

To suppress the text a **blank** has to be entered. Null or an empty sting cannot be distinguished.

An explicit text appears as entered. All other settings such as prefix, suffix, alternate measurement including alternate prefix and suffix, tolerance etc. are ignored.

But I think it would be nice to include all these settings in the default `Text` property.

**Comment by DomCR** [comment]
Perfect! I'll take a look to implement this changes.

Thanks!

**Comment by mme1950** [comment]
Hi @DomCR
including prefix and suffix, tolerance etc. requires some investigation.

This code would be half way. Shall I create PR?

		public string Text
		{
			get {
				if (this._text == " ")
				{
					return string.Empty;
				}

				if (string.IsNullOrEmpty(this._text))
				{
					double measurement = Math.Round(this.Measurement, this.Style.DecimalPlaces);
					NumberFormatInfo nfi = new NumberFormatInfo();
					nfi.NumberDecimalSeparator = this.Style.DecimalSeparator.ToString();
					return measurement.ToString(nfi);
				}

				return this._text;
			}

			set {
				this._text = value;
			}
		}

**Comment by DomCR** [comment]
Hi @mme1950,

I haven't had time to look into this.
Your code looks good for a the requirements of this issue, if you want create a PR and I'll merge this change.

We can keep this issue open for further investigation, add a TODO note inside the method to know where the changes have to be made.

**Comment by mme1950** [comment]
Hi @DomCR,

after some work with dimensions I think my proposal is not a good idea, since the generated text may be incomplete or not suitable for angular dimensions. And there is no indication, whether the text was created according to the various properties or explicitly entered. The implementation is definitely better than the existing one but works well only for linear dimensions with no special options.

The generated text must consider all settings specified in DimensionStyle including prefixes, postfixes, alternate-unit dimensioning, and tolerance. All properties may be overriden in the entity's extended data. The implementation for linear and angular dimensions must be different.

This would require implemantation of functions to read extended properties. Should this be provided by ACadSharp?

I extracted formatting of the measurement to a virtual method that cen be overidden the derived dimension classes.

**Comment by mme1950** [comment]
@DomCR 

Proposed class hierarchy:
* `Dimension`
  * `DimensionAligned`(implements `CreateMeasurementText` for aligned dimensions)
     * `DimensionLinear`
  * `DimensionOrdinate` (implements `CreateMeasurementText` for ordinate dimensions, may be identical to aligned)
  * `DimensionCircle` (new: defines common properties `AngleVerex`, `LeaderLength`)
     * `DimensionRadius` (implements CreateMeasurementText)
     * `DimensionOrdinate` (implements `CreateMeasurementText`)
  * `DimensionAngular` (new, defines common properties of `DimensionAngular3Pt` and `DimensionAngular2Line` and implements `CreateMeasurementText` for angular dimensions.)
    * `DimensionAngular3Pt`
    * `DimensionAngular2Line`

**Comment by DomCR** [comment]
The field Text is optional in the dxf documentation, meaning that is something that does not have any constrain to anything in the dimension, I would simplify the property `Text` by allowing the user decide what they want to save in the property, meaning that the property will react as specified in the documentation:

> Dimension text explicitly entered by the user. 

The user has to be able to set any value in it, even null or an empty string.

> Optional; default is the measurement. If null or “<>”, the dimension measurement is drawn as the text, if ““ (one blank space), the text is suppressed. Anything else is drawn as the text

When the system or the user get the value from the property, if is empty, null or "<>" (for some reason) the value should be the `Mesurement` using the method to `string()`

Besides the Text property, I really like the idea of the method `CreateMeasurementText()`, having a method that applies the `DimensionStyle` and returns the value that "should have" is a really good idea. As you said, this method needs to be virtual in the Dimension class so the others can make the necessary changes to write the text to better suit the type of dimension.

Let me know what you think about my approach.

**Comment by mme1950** [comment]
Yes!

I understood the process in AutoCAD so:
* AutoCAD by default displays the measurement as formatted string applying DecimalPlaces, DecimalSeparator, PostFix, ZeroHandling Alternate .., and Tolerance.
* The user can override the default measurement text (Dimension text explicitly entered by the user)
* or can enter a single blank to suppress the measurement text. 

According to the documentation I would expect, that a text explicitly entered by the user is returned in DXF with the group code 1. Otherwise this field is missing or empty in DWG. I never saw the default formatted measurement text in the DXF or DWG.

Creating a formatted measurement text would be a nice service of ACadSharp. 
I think it is a good Idea to separate this feature from the `Text` property that just reflects the data read from the DXF or DWG. I think the `Text` property should return an empty string when the AutoCAD user did not enter an explicit text, 

BTW: The sample_AC1032_ascii.dxf cantains an dimension examle with a user defined measurement text. The text does not appear in the DIMENSION entity data. This is somehow confusing,

**Comment by mme1950** [comment]
Consequently
* The `CreateMeasurementText()` must be public.
* `Text` should return the text read fro DXF or DWG.

**Comment by DomCR** [comment]
Correct! 

Also Text has to allow to set a custom value using ACadSharp

**Comment by mme1950** [comment]
Hi @DomCR,

happy New Year.

I think it is a good approach to define the ACadSharp CadObject classes as data container transparently representing data from the AutoCAD file. They should allow to get data or to set data with no interpretation or transformation. Then we have a chance that reading an writing is symmertric. Transformations, however, are required when data representation is different in DXF and DWG, but should also be symmetric.

Some/many entities are associated with a respecive style object that represents default properties for the entity. Default properties may be overridden either by dedicated properties or by extended data of the entity.

To get the effective property values the different sources of overriding values have to be considered, and various overriding rules have to be applied.

For dimension entities and Leader entities it is quite simple: The entity's extended data are to be used if available; otherwise, the default value from associated DimensionStyle object are to be used.

The MultiLeader uses properties of the MultiLeader object, the embedded ContextData objects, and the embedded Leader objects to override values. This is controlled by a list of property override flags. I do not know whether MultiLeader can have also
extended data.

A using system, e.g. our SVG renderer, must use the effective values. It would be a good service of ACadSharp to provide effective data for each entity encapsulating the various override concepts.

This requires
* a convenient mechanism to read (and maybe write) extended data,
* one class per entity providung the effective property values. This may be an extension, just providing the overridable properties, or a wrapper with all properies relevant for the entity.

**Comment by DomCR** [comment]
Hi @mme1950,

Happy new Year!!!

This feature proposal seems to be out of the scope for this particular issue, it would be better to open a new one.

About the extended data, is something that I haven't explored yet, I'll need to study how extended data affects the entities in different environments and take a look of how are you implementing it in your examples and find a proper way to integrate this feature into ACadSharp.

Thanks!

**Comment by mme1950** [comment]
Hi @DomCR,

this feature - evaluating effective properties - is prerequisite for the full implementation of the `CreateMeasurementText()` method.

**Comment by mme1950** [comment]
Hi @DomCR,

I would suggest to merge this PR to be able to distinguish `Text` explicitly entered and empty `Text`. In the latter case the measuremet text has to be created using the "effective style properties".

I spend some effort on the full implementation of the `CreateMeasurementText()` method and learned a lot. The implementation is quite complex and should not be part of the `Dimension` class or its inheritors. So the `CreateMeasurementText()` method should be removed from the `Dimension` class.

We should discuss whether the implementation should be placed in the using components such as our ACadSvg, or in ACadSharp or a separate component, to make available for everyone.

**Comment by DomCR** [comment]
I'm guessing that you are talking about this PR:
- https://github.com/DomCR/ACadSharp/pull/223

I haven't review it due the missing implementation mentioned in the PR: 

```
//	TODO Decimal places and decimal separator can be overridden by the entity's
//		 extended data.
//	TODO Add zero-handling here.
//  TODO Override this method in derived classes.
```

As for removing `CreateMeasurementText()`, I think it should be a part of the `Dimension` class the function is strictly related to all dimensions and it would be useful to have a method to retrieve the Dimension measurement text using the style applied, we can discuss further about how to implement or the placement for this method.

Let me know what you think.

**Comment by DomCR** [comment]
If a PR is not ready to be reviewed, please use the Draft so I know is a work in progress, otherwise set it as ready to review.

If I take to long, tag me in the PR so I know I have to review it.

**Comment by mme1950** [comment]
`DimensionStyle` defines a lot of options to be considered for the creation of the measurement text. All `DimensionStyle` properties can be overridden by the entity's extended data.

Please have a look at this story: https://github.com/nanoLogika/ACadSvg/issues/57

We have implemented the `CreateMeasurementText()` method in the using component (ACadSVG).
It is a lot of stuff, a lot of options and formats have to be considered:
* Two implementations of the `CreateMeasurementText()` method for linear dimension and for angular dimensions.
* The parts primary measurement, alternate unit measurement (for linear dimensions only).
* The tolerance with the variants symmetric, plus/minus, or limits.
* There are various formats that can be used for the primary and the alternate case. We have a formatter class for every format.
* We implemented a class to read the effective DimensionStyle properties that may be overridden by the entity's extended data. 

I think it would be great to include this functionality into ACadSharp rather than in the using component.
But perhaps it is wise to implement it as a separate component.

So finally I would suggest to remove the `CreateMeasurementText()` method from the `Dimension` class.
If you prefer to complete `CreateMeasurementText()` method in the `Dimension` class we must first solve a lot of design issues (see our discussion at Jan 4th).

I would like to have this issue closed becaue in the current implementation ist is impossible do distinguish between measurement text formatted from the measurement value und measurement text explicitly entered.

**Comment by mme1950** [comment]
For me it is important that `Text` returns nothing exept the user has entered an explicit dimension text.

But we must keep in mind that the implementation of `CreateMeasurementText` I have added is valid only for linear dimensions assuming decimal format.
It does not consider any options set in the dimension style or in the entity's extended data.

**Comment by mme1950** [comment]
Yes, OK.

**Comment by mme1950** [comment]
done.
