### ISSUE TITLE
Error converting from DWG to DXF

### ISSUE THREAD

**Issue by xaotix** [DomCR/ACadSharp#153]
**Describe the bug**
I'm trying to convert a DWG 2010 to DXF. But the file saved is corrupted.

**To Reproduce**

           var doc = new DwgReader("test.dwg").Read();
            var writer = new DxfWriter($"test.dxf", doc, false);
            writer.Write();

**Screenshots**
![image](https://github.com/DomCR/ACadSharp/assets/1271498/584d7a90-a46c-430e-8972-eeef07c1f81e)

**Additional context**
[test.zip](https://github.com/DomCR/ACadSharp/files/12113531/test.zip)

**Comment by DomCR** [comment]
Hi @xaotix,

I've tested your file, it seems that the refactor for the `CadHeader` writes some variables that are invalid for some versions.
I'll open a branch to fix this issue and find a better solution to write the header.
