### ISSUE TITLE
In some polylines of DWG files "IsClosed" field is false while it should be true

### ISSUE THREAD

**Issue by eugeniobidone** [DomCR/ACadSharp#159]
**Describe the bug**
Some polylines of DWG files should be closed, but the DwgReader reads them as open.

**To Reproduce**
Use the functions DwgReader.Read() on the attached files and compare the results with the attached screenshots to see the discrepancies.

**Expected behavior**
The closed profiles should be read as closed polylines instead of open.

**Screenshots**

![Newicon](https://github.com/DomCR/ACadSharp/assets/136305718/f889441f-7fec-4266-bc85-cb6fdedbf566)
![LibellulaPonticelli](https://github.com/DomCR/ACadSharp/assets/136305718/0b07b27f-dd82-4ce5-befc-1a214bbd08eb)

**Additional context**
[DwgFiles.zip](https://github.com/DomCR/ACadSharp/files/12416447/DwgFiles.zip)

**Comment by DomCR** [comment]
Hi @eugeniobidone 

I see that the flag is ignored in the reader, opening a branch to fix it.
