### ISSUE TITLE
Still throwing exceptions. 

### ISSUE THREAD

**Issue by mattbrownfaro** [DomCR/ACadSharp#163]
Hi @DomCR,

Looking MUCH better but missing objects. And throwing exceptions. [ALFA Sportwagon-4 views.zip](https://github.com/DomCR/ACadSharp/files/11728772/ALFA.Sportwagon-4.views.zip)
![Snag_2104073d](https://github.com/DomCR/ACadSharp/assets/9598498/9918c988-474f-475c-904c-ed8901110f6e)
Missing wheels and other views of the car, but geometry looks great.

This drawing is throwing a lot of exceptions. I believe it loaded in a previous ACADSharp version
[2140QUEENCITY.zip](https://github.com/DomCR/ACadSharp/files/12222797/2140QUEENCITY.zip)

Built DxfWriter-Full-refactor branch

Would you be interested in a development contract? We'd like to use this library in our fall release. It's close but still can't load a bunch of drawings that our current DWG library can. Please contact me at matt.brown@faro.com if interested.

Thanks Dom!

_Originally posted by @mattbrownfaro in https://github.com/DomCR/ACadSharp/issues/142#issuecomment-1659305567_

**Comment by DomCR** [comment]
Hi @mattbrownfaro 

The branch [DxfWriter-Full-refactor](https://github.com/DomCR/ACadSharp/tree/DxfWriter-Full-refactor) is currently in development, all the exceptions are expected, when the task is completed and merge this should work fine the **ALFA Sportwagon-4 views** file.

About the **2140QUEENCITY** is more complicated, the dxf writer that they used encoded the name of the model space in a funny way _$MODEL_SPACE_ which messes up the way that `ACadShrap` finds it.

About the missing wheels, it seems that they are drawn with polylines, for some reason the ones that the writer is generating are not valid.

I'll open 2 branches to take a look to both issues.

**Comment by DomCR** [comment]
This issue seems to be bigger than I expected, the file that is failing is because is in an older version `AC1009` which is not supported by `ACadSharp` at the moment, by now I'll add an exception to the writer to indicate that this version is not supported but it will take time do make the `DxfReader` compatible with it.
