### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by Jtfs** [DomCR/ACadSharp#2]
Hi @DomCR, very interesting project. I'm C# developer and I'd like to collaborate. How can I do it?

**Comment by DomCR** [comment]
Hi @Jtfs,

As you can see the project is a very early state, and I could use some help with it.
I will look at the best way to incorporate collaborators into the project and the best way to proceed.

I keep you informed, thank you.

**Comment by DomCR** [comment]
I added a Contributing part in the readme, is just a first step but it will do by now.
