### ISSUE TITLE
Dimension.Block property is always null

### ISSUE THREAD

**Issue by mme1950** [DomCR/ACadSharp#224]
The Dimension entity has a _Block_ property (DXF group code 2). In DXF this field contains the name of a BLOCK**_RECORD**. In DWG the reference to the BLOCK_RECORD is a handle reference.

The _Block_ property is of type _Block_ but must have the type _BlockRecord_.

Changing the type of the property and adjusting the code in CadDimensionTemplate.Buid solves the probem.

We will create a PR.

**Comment by DomCR** [comment]
Good eye! 

Opening a branch to fix.
