### ISSUE TITLE
how can I get Polyline lengt

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#233]
Hi

how can I get Polyline lengt

`  Dim reader = New DwgReader("ALLT2.dwg")
  Dim doc = reader.Read()
  Dim entities = doc.Entities

  For Each item In entities

      Dim l As LwPolyline = DirectCast(item, LwPolyline)

  Next`

**Comment by DomCR** [comment]
Hi @sigster,

I can see that you are using Visual Basic, I wrote an example using C#, hope that helps:

```C#
public static double GetPolylineLength(LwPolyline polyline)
{
	double length = 0;
	for (int i = 0; i < polyline.Vertices.Count; i++)
	{
		XY start = polyline.Vertices[i].Location;

		XY end = new XY();
		if (i + 1 == polyline.Vertices.Count - 1)
		{
			//Last one
			if (polyline.Flags.HasFlag(LwPolylineFlags.Closed))
			{
				end = polyline.Vertices.First().Location;
			}
			else
			{
				return length;
			}
		}
		else
		{
			end = polyline.Vertices[i + 1].Location;
		}

		length += start.DistanceFrom(end);
	}

	return length;
}
```
In case that the polyline has any arc in it, it will need an extra calculation to get the length.

**Comment by sigster** [comment]
Thanks
