### ISSUE TITLE
Write DWG with ACadSharp , Autocad = This drawing was saved with a student Version

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#245]
`    Dim doc As ACadSharp.CadDocument = New ACadSharp.CadDocument()
    Dim writer As ACadSharp.IO.DwgWriter = New ACadSharp.IO.DwgWriter("Test1.dwg", doc)
    writer.Write()
`

I get this messages in Autocad when I create DWG file with ACadSharp

This drawing was saved with a student Version of the product and marked with a plot stamp

**Comment by DomCR** [comment]
Hi @sigster,

This is a known issue, the `DwgWriter` is one of the newest features in the project and still needs to be polished.
Autocad seems to use some kind of watermark in the files that is difficult to replicate, I'll open a branch to take a look.

**Comment by DomCR** [comment]
If you save the file manually do you still have the plot stamp?

**Comment by sigster** [comment]
Do you mean if I save new file with Autocad no I have register Austocad
I don't have student version

**Comment by DomCR** [comment]
I mean, if you save the file created with ACadSharp using Autocad, will this re-saved file still have the stamp?

I want to know if it is something that sticks in the file or it can be removed by re-saving the file in a licensed Autocad.

**Comment by sigster** [comment]
If I open the file with autocad and save it I still get theis messages
same if I use SAVEAS

<img width="377" alt="Auvilla" src="https://github.com/DomCR/ACadSharp/assets/18507437/4b503a1b-fe1d-4d28-ac20-5c7f90674826">

**Comment by DomCR** [comment]
Ok, thanks for the info

**Comment by DomCR** [comment]
I found a bit of information about this issue:
https://help.autodesk.com/view/ACDLT/2024/ENU/?guid=GUID-A6E37575-FA05-4192-BE84-F19F8C0CE56A
It seems that for version of Autocad later than 2022 the student version won't be relevant anymore, I know that this does not fix the issue but is a workaround by now.

**Comment by DomCR** [comment]
I think that was it!

Thanks for the clue!

**Comment by DomCR** [comment]
The change is in master, please if you can confirm that the change fixed the issue.

I'm currently using a student version so it's quite hard for me to confirm that this has been completely fixed.

Thanks!

**Comment by sigster** [comment]
This did fix it !

Thanks DomCr

to skip this messages in Autocad then you can use command DWGCHECK = 0

<img width="338" alt="Ónefnt" src="https://github.com/DomCR/ACadSharp/assets/18507437/3fe3364a-6da1-4e29-a16b-bf9de80637f5">
