### ISSUE TITLE
read big dwg file take so long time

### ISSUE THREAD

**Issue by brull** [DomCR/ACadSharp#246]
when i run this program:
`var sw = new Stopwatch();
sw.Start();
using (DwgReader reader = new DwgReader(_file))
{
	doc = reader.Read();
}
sw.Stop();
Console.WriteLine(sw.ElapsedMilliseconds);`
it takes about 80175ms to read a dwg file about 24M size.

**Comment by brull** [comment]
When I use Teigha to read the same file, it takes just 2187ms. The big dwg files are usual on building design. So can you guys improve it. Thanks a lot！

**Comment by DomCR** [comment]
Hi @brull,

Can you provide a file as an example? it would be good to detect bottlenecks and have an example.

Thanks.

**Comment by brull** [comment]
> This project is still actively being developed so performance is still being worked on. Since this is an open source project and you want use it, you can create a PR and assist with that performance endeavor and everyone will appreciate it. There are some areas where the parsing can improve and I'm working on ways to help with that.

This project is great！ U are great men！Cause it‘s the only one open source project written by C#. Hope it become better and better. 
Now， I am working on rising performance on my job.

**Comment by brull** [comment]
> Hi @brull,
> 
> Can you provide a file as an example? it would be good to detect bottlenecks and have an example.
> 
> Thanks.

I'm sorry, the dwg file designed by another guy, I have no idea can I give it to u. But I think this problem is universal. U can find a big dwg file and try it.
