### ISSUE TITLE
How to get Object from a ACAD_OC Dictionary

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#248]
Hi

wonder if someone can help me with this

I need to get info about object in Dictionary

ACAD_OC
  Test - 10.02.2020 - Copy = just a path to a file
      32mm = Polyline
      600L 480mm br = block
      72 Fiber = Polylinee

<img width="474" alt="AUdic" src="https://github.com/DomCR/ACadSharp/assets/18507437/135cd889-3d59-435d-8663-a9c7c53e9cf5">

Regards
Sigster

**Comment by DomCR** [comment]
Hi @sigster 

In the image you seem to be looking at the equivalent in `ACadSharp` `CadDocument.RootDictionary`, you may be able to access into the dictionary using `CadDocument.RootDictionary["ACAD_OC"]` which I'm guessing that it will be another dictionary that you can access into their entries and get the values.

Let me know if this helps.
