### ISSUE TITLE
Grid off when I create dwg file 

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#255]
Hi

how can I have Grid off in model when I create dwg file 

<img width="447" alt="image" src="https://github.com/DomCR/ACadSharp/assets/18507437/3fd94a61-b921-4c9c-afad-3805f9f6e616">

**Comment by DomCR** [comment]
Hi @sigster 

To disable the Grid check the *Active `VPort` and disable the `ShowGrid` flag.

**Comment by sigster** [comment]
Hi

Any change you can help me with sample code

Regards
Sigster

**Comment by DomCR** [comment]
```C#
	CadDocument doc;
	using (DwgReader reader = new DwgReader(_file))
	{
		doc = reader.Read();

		//This sets the grid off for the *Active VPort
		doc.VPorts[VPort.DefaultName].ShowGrid = false;

		//This guarantees that all VPort configurations have the grid off
		foreach (VPort vp in doc.VPorts)
		{
			vp.ShowGrid = false;
		}
	}
```

Let me know if this helps.

**Comment by sigster** [comment]
This works
Thanks ComCR
