### ISSUE TITLE
Get image count from "ACAD_IMAGE_DICT"

### ISSUE THREAD

**Issue by TheRaikoz** [DomCR/ACadSharp#259]
Hi,
I get a dictionary with images, but the count is 0.
There are 6 of them in the document, something is wrong.
ACAD 2017
Please help
![Скриншот 26-01-2024 155747](https://github.com/DomCR/ACadSharp/assets/22329233/59ea34f1-7d4d-42c7-ba6b-43b68318fe4b)

**Comment by DomCR** [comment]
Hi @TheRaikoz,

Do you have a file that I can use as an example to test your case? It would help a lot to spot the issue.

Thanks.

**Comment by TheRaikoz** [comment]
Yes, here you go.
[Test.zip](https://github.com/DomCR/ACadSharp/files/14082506/Test.zip)

**Comment by TheRaikoz** [comment]
@DomCR
 I added acad Entity ImageDef and everything worked for me

**Comment by DomCR** [comment]
I've checked the logs from the reader:

Unlisted object not implemented, DXF name: IMAGE
Unlisted object not implemented, DXF name: IMAGEDEF

I'm guessing that these are the objects that you are looking for, I'll open 2 branches and see if they can be implemented in the reader.
