### ISSUE TITLE
Create new DWG, Color control and Line Type Control and Model 

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#268]
When I create new DWG

Color control = Color 0
Should it be = Bylayer as default ?

Line Type Control = notthing is default 
Should it be = Bylayer as default ?

Model and Layout1
Layout1 is Default activate
Should it be = Model as default  ?

Regards
Sigster

**Comment by DomCR** [comment]
Hi @sigster 

What do you mean by control?
Are you referring to the header variables?

**Comment by sigster** [comment]
This , when I open DWG file

<img width="442" alt="image" src="https://github.com/DomCR/ACadSharp/assets/18507437/71f2990c-8669-42a4-8f63-e90f786de18e">

**Comment by DJGosnell** [comment]
I believe you are mixing up concerns. This project gives you exact control over the DWG/DXF file reading and writing so you can make the layers or entities do whatever you want. If you are looking for GUI controls, that is out of scope of this project.  I'd suggest learning about how DWG/DXF files are used with the documentation in the Docs directory.

**Comment by DomCR** [comment]
These values are set by default but they are not constraint to anything in particular.

If you want a sort of defaults for your document you can change the values in the header of the document, here is an example with the `LineType` by default:

```C#
doc.Header.CurrentLineTypeName = LineType.ByBlockName;
```

Not sure which variable holds the current Layout, I would have to check that.

**Comment by sigster** [comment]
Thanks

Do you have sample how to change Header color to Bylayer

<img width="458" alt="image" src="https://github.com/DomCR/ACadSharp/assets/18507437/7d42a3c2-f1ce-4717-acdd-6b0de1216242">

**Comment by DomCR** [comment]
It seems that, there is a limitation with colors, the colors in the header are written in a different way than the other entities and by now the writer cannot write the colors in the header property, so by now I think that this value cannot change.

I'll open a branch assigned to this issue to take a look at this bug.

**Comment by sigster** [comment]
Thanks

and thanks for the

`doc.Header.CurrentLineTypeName = LineType.ByBlockName;`

Regards
Sigster

**Comment by sungaoyong** [comment]
> Model and Layout1
> Layout1 is Default activate
> Should it be = Model as default ?

 document.Header.ShowModelSpace = true;
