### ISSUE TITLE
Edit DWG file

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#281]
Hi

Is only option to Write and Read DWG
or can I Edit DWG file , write Changes to the file ?

**Comment by DomCR** [comment]
Hi @sigster 

You can open a file modify it as you want and save it again, I would recommend to not override the file due it may cause some information loss.

**Comment by DomCR** [comment]
This is an example of how can you add a `Layer` into a document

```C#
doc.Layers.Add(new Layer("my_layer"));
```

**Comment by DomCR** [comment]
The loss of information that you may have is due the current limitations of the library, to save a file you just have to use the `DwgWriter` or the `DxfWriter` depending on the format that you want.

**Comment by sigster** [comment]
I understand thank you  :)

**Comment by sigster** [comment]
I understand thank you :)
