### ISSUE TITLE
Hatch - boundaryPath - Edges - Polyline

### ISSUE THREAD

**Issue by instr0ng** [DomCR/ACadSharp#282]
Hi,

**Describe the bug**
I have a problem with hatching, in particular with polyline boundaries, the Bulge parameter is set for only one point and there is no way to build the correct boundary for hatching

**To Reproduce**
Create a polyline shape in the drawing with more than one arc, hatch it and read the hatch data 

**Expected behavior**
A clear and concise description of what you expected to happen if needed.

**Screenshots**
It was expected that, like polyline in Entity, each point would have its own Bulge parameter.

**Comment by DomCR** [comment]
Hi @instr0ng,

Which file format are you using? DWG or DXF?
