### ISSUE TITLE
Autocad command DIMSTYLE,  FATAL ERROR

### ISSUE THREAD

**Issue by sigster** [DomCR/ACadSharp#290]
Hi

After I create a DWG file and use the command DIMSTYLE in Autocad, autocad crashes

`
    
    Const dwgFilePath22 = "Test1.dwg"
    doc.Header.Version = ACadVersion.AC1018
    doc.Header.PointDisplayMode = 35
    doc.Header.CurrentLineTypeName = LineType.ByLayerName

    doc.VPorts(VPort.DefaultName).ShowGrid = False

    For Each vp As VPort In doc.VPorts
        vp.ShowGrid = False
    Next

    Using writer As DwgWriter = New DwgWriter(dwgFilePath22, doc)
        writer.Write()
    End Using`

![image](https://github.com/DomCR/ACadSharp/assets/18507437/59838f9b-7836-439e-ae71-fad324b61966)

Regards 
Sigster

**Comment by DomCR** [comment]
Hi @sigster 

By now to fix this issue you can use the command AUDIT.

I'll open a branch to take a look at this specific issue.
