### ISSUE TITLE
Getting error as 'An item with the same key has already been added. Key: ARIALN.TTF' when try to read dwg file

### ISSUE THREAD

**Issue by rohan515** [DomCR/ACadSharp#319]
**Describe the bug**
Getting error as 'An item with the same key has already been added. Key: ARIALN.TTF' when trying to read the dwg file, file link https://github.com/rohan515/Cad-files/blob/main/1.dwg

**To Reproduce**
![dwg1](https://github.com/DomCR/ACadSharp/assets/17959422/3180a388-299a-4baa-8f43-1a6575e51ed2)

reader.Read() producing the error.

**Comment by DomCR** [comment]
Hi @rohan515 

This is a known issue that is being addressed, I'll link the PR to this issue.

**Comment by rohan515** [comment]
Okay will be very helpful then😊

**Comment by rohan515** [comment]
Hi I have a few queries, can we connect over email or any other social media?

**Comment by rohan515** [comment]
Hi I have a few queries, can we connect over email or any other social media?

**Comment by DomCR** [comment]
Hi @rohan515,

If the query is related to the project or how to use it, please create an issue or check the [discussions](https://github.com/DomCR/ACadSharp/discussions) so anyone can read and have the information.

If is something else, let me know what it is.

Thanks.
