### ISSUE TITLE
get error when use memory stream to read files

### ISSUE THREAD

**Issue by farshadvl** [DomCR/ACadSharp#353]
hi 
I use acadsharp to read dwg files and do some process like dxf files on it.
my code:
 using (MemoryStream ms = new MemoryStream())
 {
     using (DxfWriter writer = new DxfWriter(ms, doc, false))
     {
         writer.OnNotification += onNotification;
         writer.Write();
     }
}

it get error : Cannot access a closed Stream.

what should I do?

**Comment by Revan1985** [comment]
Hi @farshadvl 
are you sure you want to read a file?
Class DxfWriter is used to write, you should use class DxfReader.

**Comment by DomCR** [comment]
Hi @farshadvl,

As @Revan1985 pointed out your piece of code seems to be incomplete for us to help, but for what you are saying you are trying to read information from a closed `Stream`, if that's the case try to create a copy of the same stream:

```C#
	using (MemoryStream ms = new MemoryStream())
	{
		CadDocument doc = new CadDocument();

		using (DxfWriter writer = new DxfWriter(ms, doc, false))
		{
			writer.CloseStream = false;
			writer.Write();
		}

		MemoryStream s = new MemoryStream(ms.ToArray());

		using(DxfReader reader = new DxfReader(s))
		{
			CadDocument output = reader.Read();
		}
	}
```

I'm not sure if this is what you are trying to achieve, let me know if this helps.

**Comment by DomCR** [comment]
I've also noticed that the writer closes the stream even if the `CloseStream` flag is set to false, I'll open a branch to fix it, in the mean time the code that I've provided should help.
