### ISSUE TITLE
Unable to read in DWG after updating ACadSharp

### ISSUE THREAD

**Issue by Lukeor** [DomCR/ACadSharp#361]
Hello,

In version 2.2.0-beta of ACadSharp I am able to successfully read in the attached DWG file.

[Milborne.zip](https://github.com/user-attachments/files/15787499/Milborne.zip)

However after updating ACadSharp to version 2.3.1-beta I now receive the following error when trying to read in the same DWG file:

![image](https://github.com/DomCR/ACadSharp/assets/162500307/4a14b623-af16-4ce1-b977-bd047ed8f5b1)

Kind regards,
Luke

**Comment by DomCR** [comment]
Hi @Lukeor,

It seems to be an issue regarding on how the `CadDictionary` handles the new `NonGraphicalObject`.

I'm creating a PR now.

Thanks for reporting the issue!
