### ISSUE TITLE
DwgWriter fails due to summaryinfo being null

### ISSUE THREAD

**Issue by Nubbit** [DomCR/ACadSharp#381]
**Describe the bug**
I have hundreds of DWG files made by a company with a custom (Autodesk authorized) solution where the summaryinfo in the CadDocument is null. DwgReader has no issue with this but when writing a new DWG file based of the CadDocument the writeSummaryInfo() method of DwgWriter fails due to the SummaryInfo being null. 

**Expected behavior**
The expected behavior would be that ReadSummaryInfo() initializes a new CadSummaryInfo object when the retrieved value from the DWG file is null as is with a newly initialized CadDocument.

**Screenshots**
![SummaryInfo](https://github.com/user-attachments/assets/76cd2042-4d7a-4ae4-bb73-b045bd10109c)

**Additional context**
I understand/expect that the DWG files are out of spec but it would be nice that DwgWriter/writeSummaryInfo() doesn't fail because of it. Sadly I am not allowed to share the DWG file.

Also, what an awesome project! Keep up the great work!

**Comment by DomCR** [comment]
Hi @Nubbit,

Your issue may be caused by this code:

```C#
	//Older versions than 2004 don't have summaryinfo in it's file
	if (this._fileHeader.AcadVersion < ACadVersion.AC1018)
		return null;
```

Older version do not have SummaryInfo, but you are right it should not be null by default.
Opening a branch to fix it.

Thanks for your support!

**Comment by Nubbit** [comment]
I wasn't paying attention to the file version but you are absolutely right! Thank you for the quick fix.
