### ISSUE TITLE
CadDictionary TryAdd always returns false

### ISSUE THREAD

**Issue by Nubbit** [DomCR/ACadSharp#388]
**Describe the bug**
The TryAdd function of CadDictionary will always return false even if the key is successfully added

```
public bool TryAdd(string key, NonGraphicalObject value)
{
	if (!this._entries.ContainsKey(key))
	{
		this.Add(key, value);
	}

	return false;
}
```

**To Reproduce**
Try to add a DictionaryVar to the RootDictionary. The return value will always be false, even though it was successfully added to the dictionary.

**Expected behavior**
Return true when key is succesfully added e.g.:

```
public bool TryAdd(string key, NonGraphicalObject value)
{
	if (!this._entries.ContainsKey(key))
	{
		this.Add(key, value);
                **return true;**
	}

	return false;
}
```

**Comment by DomCR** [comment]
Hi @Nubbit,

You are right, thanks for reporting it!

Opening a branch to fix it.
