### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by jyoubnnggg13** [DomCR/ACadSharp#389]
**Describe the bug**
trying to read the dwg and write it to dxf file, the file contains Korean text content.
the content is displayed as ' ? ' and some sort of special chars.

**Expected behavior**
Need matched encoding 

**Screenshots**
![image](https://github.com/user-attachments/assets/5216588f-5faf-4313-a67f-9c36ae9a98c8)

**Comment by jyoubnnggg13** [comment]
And I think this doc has right pagecode
![image](https://github.com/user-attachments/assets/91c6956b-8032-4b14-98b5-9e39486c6e3c)

**Comment by DomCR** [comment]
Hi @jyoubnnggg13 

I'll open a branch to take a look.

Can you provide an example file to test it?

Thanks!

**Comment by jyoubnnggg13** [comment]
@DomCR  Thanks for quick reply !

I attached the file I used in .zip ( because of not supported file extension )
+ I found another dwg that contains Korean text and has same codepage in its header ( kcs5601 ) brought  me result I expected.

Thanks :) 
[test1.zip](https://github.com/user-attachments/files/16368655/test1.zip)
