### ISSUE TITLE
Hatch Transparency Value Not Updating in DWG file

### ISSUE THREAD

**Issue by KyleeChangg** [DomCR/ACadSharp#398]
`private static Hatch CreateHatchForPolyline(IPolyline polyLine)
		{
			var transparency = new Transparency()
			{
				Value = 50
			};

			var hatchBoundaryPath = new Hatch.BoundaryPath()
			{
				Flags = BoundaryPathFlags.External, // Set appropriate flags as needed
				Entities = new List<Entity> { polyLine as Entity } // Add the polyline directly
			};

			// Create the hatch and set its properties
			var hatch = new Hatch()
			{
				Paths = new List<Hatch.BoundaryPath> { hatchBoundaryPath },
				IsSolid = true,
				Transparency = transparency,
				IsAssociative = true,
			};

			return hatch;
		}`

**Describe the bug**
In the code above, I created a function that creates hatches in relation to polyline entities with the hatch transparency value set to 50%.

<img width="862" alt="image" src="https://github.com/user-attachments/assets/ccb3352c-251d-408e-a69c-825d3912f854">

These hatches show up fine in the console when trying to write. However, in the dwg file the hatch transparency value is reset to "ByLayer" and the 50% transparency does not appear. 

<img width="740" alt="image" src="https://github.com/user-attachments/assets/89d80fab-6f59-4e3c-b8a1-f5406da6849c">

**Comment by KyleeChangg** [comment]
@DomCR Any pointers for where I can find when the hatch values are written to the document?

**Comment by DomCR** [comment]
Hi @KyleeChangg,

I've been looking at this issue, I'll need to open a branch to explore it further, for the DXF the transparency value is not implemented, and for the DWG it seems that there is an error in the method `WriteEnColor` the transparency value doesn't seem to take any effect on the entity written.

Thanks for the report!
