### ISSUE TITLE
How to get attribute Tag ?

### ISSUE THREAD

**Issue by marasulov** [DomCR/ACadSharp#405]
Can't get attribute tag from block reference.

```cs
CadDocument doc = DwgReader.Read(_file);
foreach (Insert insert in doc.Entities.OfType<Insert>())
{
	foreach (var attribute in insert.Attributes)
	{
		Console.WriteLine($"{attribute.Tag} - {attribute.Value}");
	}
}
```

Have to return attribute tag and value, but returned only values
**Screenshots**

![image](https://github.com/user-attachments/assets/23a474a8-013c-4c44-82b3-c565aeee4a31)

**Comment by DomCR** [comment]
Hi @marasulov,

I've run your code in one of my files:

![image](https://github.com/user-attachments/assets/fcedc163-3b9e-4cf1-84e1-d5b6ac8c814a)

The tag and value are there as expected.

Are you reading a dxf or a dwg? 
Could you provide the file that is not working or an example?

Thanks!

**Comment by DomCR** [comment]
There is a missing implementation for multiline atts, I'll open a branch for an investigation an fix.
