### ISSUE TITLE
The entity color is incorrect in the saved DWG file

### ISSUE THREAD

**Issue by xmap2008** [DomCR/ACadSharp#407]
打开一个有颜色实体的DWG文件，即可保存，实体颜色变了。
源图
![image](https://github.com/user-attachments/assets/798a39f0-a421-4c00-a793-722d4035bf59)

保存后
![image](https://github.com/user-attachments/assets/776b2291-204d-46d0-9c86-5a5732912920)

源文件
[t.zip](https://github.com/user-attachments/files/16504206/t.zip)

代码
        static void Main(string[] args)
        {
            string path = @"D:\tmp\t.dwg";
            CadDocument doc = DwgReader.Read(path);
            using (DwgWriter writer = new DwgWriter(@"D:\tmp\t1.dwg", doc))
            {
                writer.Write();
            }
        }

**Comment by DomCR** [comment]
hi @xmap2008,

Could you translate the issue to English.

Thanks!

**Comment by xmap2008** [comment]
The entity color is incorrect in the saved DWG file

**Comment by DomCR** [comment]
I've found an issue in the Color Struct, opening a branch to fix it.

Thanks!
