### ISSUE TITLE
The class library generated an error

### ISSUE THREAD

**Issue by 2420228300** [DomCR/ACadSharp#44]
I can't run this instance project, ACadSharp class library in the various errors, is my use of the method wrong?

**Comment by DomCR** [comment]
Hi @2420228300,

can you give some details about the error that you are getting, like a piece of code or the exception.

Thanks

**Comment by 2420228300** [comment]
![image](https://user-images.githubusercontent.com/53279456/180696123-3491f058-a3b7-49ac-9f0d-da02bf7bb636.png)

**Comment by DomCR** [comment]
This errors seem to be due a missing assembly, they all say that some part is not found or duplicated, check your project `ConsoleApp1` or create a new one that is clean and make sure that is well generated, then add the project reference.

The error `CS0579` says Duplicate 'attribute' attribute and is linked to `global::System.Runtime.Versioning.TargetFrameworkAttribute` this is a core assembly, you may have duplicated references to a framework.

**Comment by 2420228300** [comment]
Thank you very much for your answer I have successfully run the project, but how do I get all the text information in cad from the doc object? Is there any documentation for this?

**Comment by 2420228300** [comment]
I've found it, thank you very much

**Comment by DomCR** [comment]
For more information here is a project with some examples:
https://github.com/DomCR/ACadSharp/tree/master/ACadSharp.Examples

**Comment by 2420228300** [comment]
ok
