### ISSUE TITLE
Examples Not Found

### ISSUE THREAD

**Issue by thaiguer** [DomCR/ACadSharp#441]
**Describe the bug**
Cant find the examples of use.

**To Reproduce**
Click in the link: https://github.com/DomCR/ACadSharp/tree/master/ACadSharp.Examples.
The link is in the README.me file. See the image bellow:
![image](https://github.com/user-attachments/assets/eda75694-ff43-4d76-aa1c-ac9d6994bc4e)

The following result is shown after click on the link:
![image](https://github.com/user-attachments/assets/0260c832-f105-4b9b-96ce-2101245ca5cb)

**Comment by DomCR** [comment]
Hi @thaiguer,

The error is due a project restructure, I'll open a branch to fix it.

Thanks for reporting it!
