### ISSUE TITLE
netstandard2.0 support

### ISSUE THREAD

**Issue by mdmozibur** [DomCR/ACadSharp#455]
A lot of project is still using netstandard2.0.
Targeting that will be beneficial to more developers.
Besides, not a lot code change is required.

I will submit a PR ASAP.

**Comment by DomCR** [comment]
Hi @mdmozibur,

If the change is minimal I won't have a problem to merge the PR, although I think is beneficial for other projects to update to higher versions of netstandard.

**Comment by mdmozibur** [comment]
@DomCR , create the pull request : [here](https://github.com/DomCR/ACadSharp/pull/483).
Just check it, only2 /3 lines of code changed.
