### ISSUE TITLE
Color not loaded properly for Solid Fill Hatch in DWG file

### ISSUE THREAD

**Issue by mdmozibur** [DomCR/ACadSharp#487]
[hatch color.zip](https://github.com/user-attachments/files/17696129/hatch.color.zip)
Load the attached file.

The file contains a very simple hatch with solid fill.
While the hatch specific properties are loaded correctly, the color loaded is `ByBlock` , but the color should be `RAL 6018`

![image](https://github.com/user-attachments/assets/b0279ad9-0e67-4864-84d3-9561157f5e6a)

**Comment by DomCR** [comment]
Hi @mdmozibur,

It seems that this Hatch is using a DBCOLOR which is not yet implemented. This object is undocumented but I'll try to implement it.

I'll open a PR to fix it.

Thanks for the report!
