### ISSUE TITLE
Single Hatch entity DWG loads in True View but not in ACadSharp

### ISSUE THREAD

**Issue by mattbrownfaro** [DomCR/ACadSharp#49]
Hi Dom,

When I read this DWG the BoundaryPath Edges and Entites are empty. I can't find any vector information in the hatch entity. It loads in True View and another cad package. Could you take a quick look and tell me if the data is there or not?

Thank you

[Hatch.zip](https://github.com/DomCR/ACadSharp/files/9263486/Hatch.zip)

**Comment by DomCR** [comment]
Hi @mattbrownfaro,

I've looked at the file, it seems that there are some errors in the Hatch reading for dwg, I'll open a branch to solve this issue.

Thanks

**Comment by mattbrownfaro** [comment]
Thank you Albert
