### ISSUE TITLE
Read DimensionAligned bug

### ISSUE THREAD

**Issue by SangIk-Lee** [DomCR/ACadSharp#501]
**Describe the bug**

DIMENSION_LINEAR recognizes the type DimensionAligned.

**Comment by SangIk-Lee** [comment]
When saving a DWG file, dimension objects are not visible. If you select all objects using Ctrl + A, the objects are selected, but the dimension objects' properties are not saved correctly. This issue seems to require correction as well.

**Comment by DomCR** [comment]
Hi @SangIk-Lee,

I'll apply the change to the reader, thanks for the report.

I'll need to investigate about the writing problem, I think is related to the block associated to the dimension.

**Comment by DomCR** [comment]
What version of the library are you using?

What dimensions are you writing?

This is what I got by adding a simple dimension to a file:
![image](https://github.com/user-attachments/assets/a4ebf371-be36-40a2-8330-cf44a251820a)

**Comment by SangIk-Lee** [comment]
I did not draw the dimension objects myself but instead used AutoCAD to create 'DimensionLinear' and 'DimensionAligned' in a DWG file. However, when I read the file using DwgReader and saved it using DwgWriter, it did not work properly.

![image](https://github.com/user-attachments/assets/e9e09da6-e8e5-4033-882c-d76a373770a2)
