### ISSUE TITLE
Can not set HatchPattern line.Angle and Offset 

### ISSUE THREAD

**Issue by sungaoyong** [DomCR/ACadSharp#504]
I used ACadSharp to create a CAD document, and in the code I manipulated the Hatch object and filled it with the appropriate symbols. Since ACadSharp does not have built-in symbols such as ANSI31, I created a new HatchPattern object called "ANSI31". However, I need to assign values to the Angle and Offset properties of this Pattern. hatch.Pattern = new HatchPattern("ANSI31");

hatch.Pattern.Scale = 10;
PatternLine line = new PatternLine();
line.Angle = 0.7853981633974;
line.Offset = new XY(-0.2245064030267288, 0.2245064030267288); 

However, these values are internal and cannot be modified in the code, so it might be worth considering the following options:

1. Supporting built-in symbols, which can be found in the dxf provided by QCAD, which is based on LibreCAD/librecad/support/patterns/.
2. Allowing write access to these properties.

**Comment by DomCR** [comment]
Hi @sungaoyong 

This properties should not be marked as internal, I'll make the change to fix them.

Thanks for the report!
