### ISSUE TITLE
Polygon contains an Arc Segment, wrong reading vertices

### ISSUE THREAD

**Issue by mahmoudadel54** [DomCR/ACadSharp#62]
This is the drawn polygon in cad file.

![image](https://user-images.githubusercontent.com/58145645/204262984-ac09244a-9e2f-4d3d-a6f5-23029fff3322.png)

And this is the output shape after reading it using ACadSharp:

![image](https://user-images.githubusercontent.com/58145645/204264787-43613b7f-34cb-42f5-b48e-e19ac6e0efe2.png)

and there isn't any indicator for the arc segment like [Center, startAngle, endAngle, Radius]

I think there is a bug in reading polygon contains arc because I tried to read an arc shape [a separate arc ] like this:
![image](https://user-images.githubusercontent.com/58145645/204265651-278df456-4ff0-48cc-a613-141e1fbd0e4f.png)

**Comment by mahmoudadel54** [comment]
1- I have drawn a closed PolyLine starting with line [I drew 3 continious lines] and closed with ARC
so the result from AcadSharp is closed polygon from 4 lines so it ignored the ARC segment 

2- the second note is I tried to draw Pure ARC using arc command in cad and the result is some indicators that this is an ARC like center, radius ..etc

So the problem is when the ARC being part of a shape, it is ignored and if it is drawn separately, it is read well

**Comment by DomCR** [comment]
The data seems to be there the problem is that Polyline vertices in Autocad create angles using this property:

```CSharp
/// <summary>
/// The bulge is the tangent of one fourth the included angle for an arc segment, made negative if the arc goes clockwise from the start point to the endpoint.A bulge of 0 indicates a straight segment, and a bulge of 1 is a semicircle
/// </summary>
[DxfCodeValue(DxfReferenceType.Optional, 42)]
public double Bulge { get; set; } = 0.0;
```

I'll open a branch linked to this issue to calculate the values of the center, radius and angle of an arc in a segment of a polyline.
