### ISSUE TITLE
Incorrect Dxf Subclass Marker

### ISSUE THREAD

**Issue by gktval** [DomCR/ACadSharp#64]
In the DxfSubclassMarker class https://github.com/DomCR/ACadSharp/blob/master/ACadSharp/DxfSubclassMarker.cs, then PolylineVertex constant has a whitespace at the end. This prevents it from ever matching the string in the file.

**Comment by DomCR** [comment]
Hi @gktval,

Thanks a lot for spotting this issue, I've created a branch to handle it.
