### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Setcad** [DomCR/ACadSharp#67]
This error occurs while opening the attached DWG file. Thanks.
[11katli.zip](https://github.com/DomCR/ACadSharp/files/10116280/11katli.zip)

System.IndexOutOfRangeException: 'Index was outside array bounds.'

**Comment by DomCR** [comment]
This issue will be solved in : https://github.com/DomCR/ACadSharp/issues/71#issue-1469246831
