### ISSUE TITLE
System.Exception

### ISSUE THREAD

**Issue by Setcad** [DomCR/ACadSharp#68]
System.Exception: Exception of type 'System.Exception'
the file: 
[FULL.zip](https://github.com/DomCR/ACadSharp/files/10116323/FULL.zip)

**Comment by DomCR** [comment]
I've found where the Exception is thrown but it will need further investigation.

This branch will ignore any objects that cannot be read by some issues like this : https://github.com/DomCR/ACadSharp/tree/Reader-failsafe

Is not a proper solution for this issue but it will allow to read the rest of the document ignoring the affected object.
